version: '3.8'

services:
  quicknote:
    build: .
    container_name: quicknote
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production

volumes:
  data: