version: '3.8'

services:
  quicknote:
    build: .
    container_name: quicknote
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    user: nobody  # 明确指定用户

volumes:
  data: